version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - 8000:8000

  backend:
    build:
      context: .  
      dockerfile: Dockerfile.backend
    ports:
      - 5000:5000
    depends_on:
      - frontend
